# Your name and what you do
name: Sinclair Liang
bio: Software Engineer in Training

description: Sinclair Liang's Personal Website

# Profile picture
picture: Sinclair/blob/master/assets/images/profile1.jpg?raw=true


# your url: http://USERNAME.github.io
url: https://github.com/sinclairliang

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
# twitter: mytwitter
linkedin: sinclair-liang-21b6278b/
github: sinclairliang
email: sinclair@sinclairliang.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Data Structures
    - Algorithms
    - TCP/IP network protocols
    - HTML, CSS
    - Python
    - Bash
    - Java & C
    - MySQL & MongoDB 
    - Git & Github
    - Linux/UNIX 
    - Postman


# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Online Store Price Tracker:
        name: Online Store Price Tracker(on going)
        description: An online application that can monitor prices and notifies users once prices reach
        url: https://github.com/sinclairliang/Online_Store_Price_Tracker
    Python Based Automated Grader:
        name: Python Based Automated Grader
        description: A python program to automate the grading process for my grader position
        url: https://github.com/sinclairliang/Python-Grader
    Arbitrary Precision Arithmetic:
        name: Arbitrary Precision Arithmetic
        description: Built a data type in Java and C to avoid overflow in mathematical calculations
        url: https://github.com/sinclairliang/Coursework/tree/master/CMPS101/CMPS101S18PA1

    Theries of Substance:
        name: Sketching or Painting? Theories of Substances
        description: A comparison essay talks different theories on Substances, especially in this digital era
        url: https://www.keepandshare.com/doc15/19501/sketching-or-painting-theories-of-substances-pdf-183k?da=y

    Research Paper:
        name: Bridging Eastern and Western philosophy
        description: A research paper talks about connections and commonalities between Western and Eastern philosophy, focusing on Tao Te Ching and Pre-Socratic philosopher Heraclitus. Mainly on Ontology and Metaphysics. 
        url: https://www.keepandshare.com/doc15/19500/research-paper-pdf-118k?da=y

    On Perfection:
        name: On Perfection
        description: Essay talks about Perfection in Lebniz's monadology framwork
        url: https://www.keepandshare.com/doc15/19499/on-perfection-pdf-67k?da=y
    Of Personal Identity:
        name: Of Personal Identity
        description: Essay talks about constants in Identity in this ever evolving reality 
        url: https://github.com/sinclairliang/Sinclair/blob/master/assets/essays/Of_Personal_Identity.pdf?raw=true


# do you want to display the theme attribution? true or false
footer: true

# Google Analytics
google_analytics: UA-126214763-1

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
